DROP TABLE IF EXISTS clients;

CREATE TABLE clients (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nome VARCHAR(45) NOT NULL,
    doc VARCHAR(15) NOT NULL,
    mail VARCHAR(30) NOT NULL,
    logradouro VARCHAR(45) NOT NULL,
    bairro VARCHAR(20) NOT NULL,
    cidade VARCHAR(20) NOT NULL,
    estado VARCHAR(2) NOT NULL,
    inscRural VARCHAR(15) NOT NULL,
    tel VARCHAR(15) NOT NULL
);